### ISSUE TITLE
How to append content to a file?

### ISSUE THREAD

**Issue by egottardo** [Znapi/scratchx-file-io#1]
Hi,
There is a way to append content to a existing file?

Thanks in advance..
Ernani Gottardo
@Znapi

**Comment by Znapi** [comment]
You could just do [write (join (read from file [foo.txt]) [text to append here]) to file [foo.txt]], but if you want a newline to be added before appending to the file, that may be a little trickier.

Now that you mention it, I'll look into adding an append block sometime soon, hopefully tomorrow. It's too late in the night right now.

**Comment by Znapi** [comment]
Sorry it took a month to finally get to it, but the latest versions of the extension and the helper app now support appending to files, and a reporter that reports a simple newline character has been added. I'm not sure if the newline works well with Windows though. Cross-platform compatibility was the reason I held off on implementing it before.

**Comment by egottardo** [comment]
Thank you, @Znapi  for your attention..This should be a great feature.
